# aliases
alias ll='ls -alFG'
alias la='ls -AG'
alias l='ls -CFG'
alias ls='ls -G'
alias mv='mv -i'
alias rm='rm -i'

# Local Postgresql
export PATH=/Library/PostgreSQL/10/bin:$PATH

# EMACS
export EDITOR=emacs

# GPG Agent
# eval $(gpg-agent --daemon --allow-preset-passphrase)
export PATH="/usr/local/opt/gpg-agent/bin:$PATH"
export GPG_TTY=$(tty)

# Conda
. ~/miniconda3/etc/profile.d/conda.sh

# Haskell/Stack
export PATH=~/.local/bin:$PATH

# Rust/Cargo
source $HOME/.cargo/env

# NPM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Zsh Completions
fpath=(/usr/local/share/zsh-completions $fpath)
plugins=(zsh-completions)
autoload -U compinit && compinit

# You may also need to force rebuild `zcompdump`:
#  rm -f ~/.zcompdump; compinit

# Zshell Pure
autoload -U promptinit && promptinit
prompt pure

# aliases
source $HOME/.aliases

# Kubectl context
NEWLINE=$'\n'
source ~/open_source/kube-ps1/kube-ps1.sh
PROMPT='$(kube_ps1)${NEWLINE}'$PROMPT
# kubernetes tab-completions!
source <(kubectl completion zsh)

# Additionally, if you receive "zsh compinit: insecure directories" warnings when attempting
# to load these completions, you may need to run this:

#  chmod go-w '/usr/local/share'
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Java
export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-10.jdk

# Go
export GOPATH=$HOME/go

export PATH=$GOPATH/bin:$PATH

# From ~/.aliases...
alias last-tags='git tag -n  --sort=-creatordate | head -n 10'
alias da="conda deactivate"
alias expy='exa -I "__pycache__|*pyc|*.py~" -T'
